### PR TITLE
Fix build and runtime issues

### PR DESCRIPTION
**Pull request by toolboc**
x-retro tag is not building or running appropriately as-is due to mismatched package.json and issues in the current player.coffee.  These changes allow for proper build of all supported cores.  README to be updated.

### CODE REVIEW

**Comment by matthewbauer** [comment]
I'll try to review this over the weekend. I need to look through all that's going on in x-retro, I really haven't looked at this code base in a while. Mostly it looks okay. Version updates, changes to build script, etc. I have no problem with.

I realize now that I didn't document that only snes9x cores worked with custom elements. I'll add some documentation on the limits on that to make things clearer.

The one thing that concerns me are the changes to player.coffee. Are you sure that the reversion is what fixes your issues? Most likely it's just a small part of those recent changes that are causing a problem. We should try to identify what that is because definitely many of those changes are good changes.

**Comment by toolboc** [comment]
I mostly tried to follow the instructions verbatim for getting started with the project and realized there have been quite a few interesting paths taken to make this project come together.  It is really amazing and allowed me to learn alot about WASM.

The changes here allowed me to successfully build from scratch on stock Ubuntu and Bash on Windows.

> I realize now that I didn't document that only snes9x cores worked with custom elements

I was able to combine all available cores into a single package with minor changes to the build script.  The result is ability to leverage multiple core types in a single element.  Nestopia core also seems to work in Edge.  Here is a quick demo: http://wasmemulators.azurewebsites.net

Given the success so far, I'm interested in adding a new core to your retrojs project.  Do you have a suggestion on something to start with?

**Comment by matthewbauer** [comment]
> allowed me to learn alot about WASM

It's actually not truly WASM. Emscripten produces "asm.js" code which is just Javascript- so browsers don't need special support for it. Eventually, Emscripten will support [WASM](https://github.com/kripken/emscripten/wiki/WebAssembly) but last I checked it wasn't fully supported. The basic idea is the same though and WASM will hopefully lead to better optimizations and performance.

As far as adding cores, you should look at some open issues:

https://github.com/matthewbauer/retrojs/issues?q=is%3Aissue+is%3Aopen+label%3Acore

All of those I attempted at some point but gave up for different reasons. Lots of platforms are tricky because they require some BIOS files to work and I've never really written that kind of thing at the JS level. SNES, NES, and GBA emulators seem to be the best supported and virtually all have reverse engineered BIOS. Most of the emulators have repos in the libretro org:

https://github.com/libretro

When a new core starts working, I've been placing them in https://github.com/matthewbauer/retrojs/tree/master/core as git submodules. Sometimes small commits (https://github.com/matthewbauer/gambatte/commit/8338c6b1a7d30206289472e79563abcaa37f2b01) are needed to get them working but they shouldn't be too significant so we can use all of the new changes from upstream. Ideally I would keep those submodules up to date with upstream but I haven't had time recently.

I know it's poorly documented but here's a description of the repos:

- retrojs - Compiles and packages cores using Emscripten
- x-retro - The "player" for the cores that acts like a libretro frontend. This provides a fairly simple custom element interface that is meant to work like the "video" tag.
- gametime-player - HTML wrapper around x-retro to play the user's game. The main source for https://matthewbauer.us/gametime-player/ and https://chrome.google.com/webstore/detail/gpemu/jhficiigpnhhaojldmanflihieepanbb (minor changes in branches currently).

**Comment by matthewbauer** [comment]
> Nestopia core also seems to work in Edge.

Nice! Last I had checked Edge had some issues with WebGL but maybe those have been fixed? I assume you have tried snes9x-next and vba-next as well? Both of those are probably the only two I've ever gotten adequate performance out of but there are some peculiarities with them that might cause some issues on Edge.

**Comment by toolboc** [comment]
> It's actually not truly WASM

Correct, I recently discovered the concept and have been digging into some of the tooling to get a deeper grasp.  This required doing some research and getting hands-on with LLVM and Emscripten.  I figured transpiling emulators would be a cool application of WASM down the road and stumbled across your projects.  I imagine it wouldn't be that much of a leap to pure WASM as Emscripten already supports on the fly compilation of asm.js to WASM.

>I had checked Edge had some issues with WebGL but maybe those have been fixed? I assume you have tried snes9x-next and vba-next as well? B

There are indeed rendering issues with snes9x-next in Edge. This is probably due to the implementation of WebGL, I may take a deeper look into it to see what can be done.

FYI 

Here are some benchmarks using a light-weight launcher (build.js) with a single dependency bundle (bundle.js) hosted on a remote server.  I hope this doesn't steer this project into the wrong direction, but I imagine a self-contained package with no need for external dependencies is an ideal way to achieve a <retro> tag served remotely into user's browser.  Curious your thoughts on this approach.  

1. Using bundle.js containing all supported cores:
image

2. Using bundle.js containing support for **only** snes9x-vnext:
image

I also noticed that using the current x-retro.js hosted at https://matthewbauer.us/x-retro.js, there is a dependency on locally installed packages.  As a result, following the instructions in the README will produce the following:

image


Using a packaged bundle and light-weight loader, this is all you need to launch a core in the browser =)
```
<head>
<script src="http://wasmemulators.azurewebsites.net/build.js"></script>
</head>
<body>
<canvas is="x-retro" src="/game.sfc" core="snes9x-next" autostart></canvas>
</body>
```

**Comment by toolboc** [comment]
player.coffee is now fixed, the following changes from 0a4ce31 appear to be the culprit.  It looks like the game was never loading as the call to do so was removed.

image

**Comment by matthewbauer** [comment]
Merged in 52a6e8819e8ea703c3b2275feb5c669e1ebfb9a0

**Pull request closed without merging**
